FROM python:3.9

# Add image info
LABEL org.opencontainers.image.source https://github.com/ranking-agent/trapi-throttle

# set up requirements
WORKDIR /app

# Install redis
RUN apt update &&\
    apt -y install --no-install-recommends redis-server &&\
    apt clean && rm -rf /var/lib/apt/lists/*

# Normal requirements
ADD requirements-lock.txt .
RUN pip install -r requirements-lock.txt

# Testing requirements
ADD requirements-test-lock.txt .
RUN pip install -r requirements-test-lock.txt

# Copy in files
ADD . .

# Set default command
ENTRYPOINT "pytest"